#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifeDiver.MODEL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mergulho")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAGENDAMENTO(AGENDAMENTO instance);
    partial void UpdateAGENDAMENTO(AGENDAMENTO instance);
    partial void DeleteAGENDAMENTO(AGENDAMENTO instance);
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertCLIENTE_CURSO(CLIENTE_CURSO instance);
    partial void UpdateCLIENTE_CURSO(CLIENTE_CURSO instance);
    partial void DeleteCLIENTE_CURSO(CLIENTE_CURSO instance);
    partial void InsertCURSO(CURSO instance);
    partial void UpdateCURSO(CURSO instance);
    partial void DeleteCURSO(CURSO instance);
    partial void InsertEQUIPAMENTO(EQUIPAMENTO instance);
    partial void UpdateEQUIPAMENTO(EQUIPAMENTO instance);
    partial void DeleteEQUIPAMENTO(EQUIPAMENTO instance);
    partial void InsertEQUIPAMENTO_VENDA(EQUIPAMENTO_VENDA instance);
    partial void UpdateEQUIPAMENTO_VENDA(EQUIPAMENTO_VENDA instance);
    partial void DeleteEQUIPAMENTO_VENDA(EQUIPAMENTO_VENDA instance);
    partial void InsertINSTRUTOR(INSTRUTOR instance);
    partial void UpdateINSTRUTOR(INSTRUTOR instance);
    partial void DeleteINSTRUTOR(INSTRUTOR instance);
    partial void InsertPACOTE(PACOTE instance);
    partial void UpdatePACOTE(PACOTE instance);
    partial void DeletePACOTE(PACOTE instance);
    partial void InsertSUPLEMENTO(SUPLEMENTO instance);
    partial void UpdateSUPLEMENTO(SUPLEMENTO instance);
    partial void DeleteSUPLEMENTO(SUPLEMENTO instance);
    partial void InsertSUPLEMENTO_PACOTE(SUPLEMENTO_PACOTE instance);
    partial void UpdateSUPLEMENTO_PACOTE(SUPLEMENTO_PACOTE instance);
    partial void DeleteSUPLEMENTO_PACOTE(SUPLEMENTO_PACOTE instance);
    partial void InsertVENDA(VENDA instance);
    partial void UpdateVENDA(VENDA instance);
    partial void DeleteVENDA(VENDA instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::LifeDiver.MODEL.Properties.Settings.Default.MergulhoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VW_AGENDAMENTO> VW_AGENDAMENTOs
		{
			get
			{
				return this.GetTable<VW_AGENDAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<VW_CURSO> VW_CURSOs
		{
			get
			{
				return this.GetTable<VW_CURSO>();
			}
		}
		
		public System.Data.Linq.Table<VW_CLIENTE_CURSO> VW_CLIENTE_CURSOs
		{
			get
			{
				return this.GetTable<VW_CLIENTE_CURSO>();
			}
		}
		
		public System.Data.Linq.Table<VW_SUPLEMENTO_PACOTE> VW_SUPLEMENTO_PACOTEs
		{
			get
			{
				return this.GetTable<VW_SUPLEMENTO_PACOTE>();
			}
		}
		
		public System.Data.Linq.Table<AGENDAMENTO> AGENDAMENTOs
		{
			get
			{
				return this.GetTable<AGENDAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTEs
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<CLIENTE_CURSO> CLIENTE_CURSOs
		{
			get
			{
				return this.GetTable<CLIENTE_CURSO>();
			}
		}
		
		public System.Data.Linq.Table<CURSO> CURSOs
		{
			get
			{
				return this.GetTable<CURSO>();
			}
		}
		
		public System.Data.Linq.Table<EQUIPAMENTO> EQUIPAMENTOs
		{
			get
			{
				return this.GetTable<EQUIPAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<EQUIPAMENTO_VENDA> EQUIPAMENTO_VENDAs
		{
			get
			{
				return this.GetTable<EQUIPAMENTO_VENDA>();
			}
		}
		
		public System.Data.Linq.Table<INSTRUTOR> INSTRUTORs
		{
			get
			{
				return this.GetTable<INSTRUTOR>();
			}
		}
		
		public System.Data.Linq.Table<PACOTE> PACOTEs
		{
			get
			{
				return this.GetTable<PACOTE>();
			}
		}
		
		public System.Data.Linq.Table<SUPLEMENTO> SUPLEMENTOs
		{
			get
			{
				return this.GetTable<SUPLEMENTO>();
			}
		}
		
		public System.Data.Linq.Table<SUPLEMENTO_PACOTE> SUPLEMENTO_PACOTEs
		{
			get
			{
				return this.GetTable<SUPLEMENTO_PACOTE>();
			}
		}
		
		public System.Data.Linq.Table<VENDA> VENDAs
		{
			get
			{
				return this.GetTable<VENDA>();
			}
		}
		
		public System.Data.Linq.Table<VW_EQUIPVENDA> VW_EQUIPVENDAs
		{
			get
			{
				return this.GetTable<VW_EQUIPVENDA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_AGENDAMENTO")]
	public partial class VW_AGENDAMENTO
	{
		
		private int _CodAgendamento;
		
		private string _CPFCliente;
		
		private System.Nullable<int> _QtdPessoas;
		
		private System.Nullable<System.DateTime> _DateRegistro;
		
		private System.Nullable<System.DateTime> _DataAgendada;
		
		private System.Nullable<int> _QtdPessoasSemEquipamento;
		
		private string _CliNome;
		
		private string _PacNome;
		
		private System.Nullable<decimal> _agendaPrecoTotal;
		
		private System.Nullable<decimal> _Preco;
		
		public VW_AGENDAMENTO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodAgendamento", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodAgendamento
		{
			get
			{
				return this._CodAgendamento;
			}
			set
			{
				if ((this._CodAgendamento != value))
				{
					this._CodAgendamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCliente", DbType="NVarChar(14) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CPFCliente
		{
			get
			{
				return this._CPFCliente;
			}
			set
			{
				if ((this._CPFCliente != value))
				{
					this._CPFCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdPessoas", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> QtdPessoas
		{
			get
			{
				return this._QtdPessoas;
			}
			set
			{
				if ((this._QtdPessoas != value))
				{
					this._QtdPessoas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRegistro", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DateRegistro
		{
			get
			{
				return this._DateRegistro;
			}
			set
			{
				if ((this._DateRegistro != value))
				{
					this._DateRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAgendada", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DataAgendada
		{
			get
			{
				return this._DataAgendada;
			}
			set
			{
				if ((this._DataAgendada != value))
				{
					this._DataAgendada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdPessoasSemEquipamento", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> QtdPessoasSemEquipamento
		{
			get
			{
				return this._QtdPessoasSemEquipamento;
			}
			set
			{
				if ((this._QtdPessoasSemEquipamento != value))
				{
					this._QtdPessoasSemEquipamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliNome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string CliNome
		{
			get
			{
				return this._CliNome;
			}
			set
			{
				if ((this._CliNome != value))
				{
					this._CliNome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PacNome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string PacNome
		{
			get
			{
				return this._PacNome;
			}
			set
			{
				if ((this._PacNome != value))
				{
					this._PacNome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agendaPrecoTotal", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> agendaPrecoTotal
		{
			get
			{
				return this._agendaPrecoTotal;
			}
			set
			{
				if ((this._agendaPrecoTotal != value))
				{
					this._agendaPrecoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preco", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Preco
		{
			get
			{
				return this._Preco;
			}
			set
			{
				if ((this._Preco != value))
				{
					this._Preco = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_CURSO")]
	public partial class VW_CURSO
	{
		
		private string _InstruNome;
		
		private int _CodCurso;
		
		private string _Nome;
		
		private System.Nullable<int> _Horas;
		
		private System.Nullable<decimal> _Preco;
		
		private System.Nullable<int> _NumeroPessoasTurma;
		
		public VW_CURSO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstruNome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string InstruNome
		{
			get
			{
				return this._InstruNome;
			}
			set
			{
				if ((this._InstruNome != value))
				{
					this._InstruNome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCurso", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodCurso
		{
			get
			{
				return this._CodCurso;
			}
			set
			{
				if ((this._CodCurso != value))
				{
					this._CodCurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Horas
		{
			get
			{
				return this._Horas;
			}
			set
			{
				if ((this._Horas != value))
				{
					this._Horas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preco", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Preco
		{
			get
			{
				return this._Preco;
			}
			set
			{
				if ((this._Preco != value))
				{
					this._Preco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPessoasTurma", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NumeroPessoasTurma
		{
			get
			{
				return this._NumeroPessoasTurma;
			}
			set
			{
				if ((this._NumeroPessoasTurma != value))
				{
					this._NumeroPessoasTurma = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[VW_CLIENTE-CURSO]")]
	public partial class VW_CLIENTE_CURSO
	{
		
		private string _CliNome;
		
		private string _CursoNome;
		
		private int _CodCurso;
		
		private string _CPFCliente;
		
		private System.Nullable<System.DateTime> _DataMatricula;
		
		private string _Turma;
		
		public VW_CLIENTE_CURSO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CliNome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string CliNome
		{
			get
			{
				return this._CliNome;
			}
			set
			{
				if ((this._CliNome != value))
				{
					this._CliNome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoNome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string CursoNome
		{
			get
			{
				return this._CursoNome;
			}
			set
			{
				if ((this._CursoNome != value))
				{
					this._CursoNome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCurso", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodCurso
		{
			get
			{
				return this._CodCurso;
			}
			set
			{
				if ((this._CodCurso != value))
				{
					this._CodCurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCliente", DbType="NVarChar(14) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CPFCliente
		{
			get
			{
				return this._CPFCliente;
			}
			set
			{
				if ((this._CPFCliente != value))
				{
					this._CPFCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataMatricula", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DataMatricula
		{
			get
			{
				return this._DataMatricula;
			}
			set
			{
				if ((this._DataMatricula != value))
				{
					this._DataMatricula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turma", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Turma
		{
			get
			{
				return this._Turma;
			}
			set
			{
				if ((this._Turma != value))
				{
					this._Turma = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[VW_SUPLEMENTO-PACOTE]")]
	public partial class VW_SUPLEMENTO_PACOTE
	{
		
		private int _CodPacote;
		
		private int _CodSuplemento;
		
		private System.Nullable<int> _Quantidade;
		
		private string _Nome;
		
		private System.Nullable<int> _QtdDisponivel;
		
		public VW_SUPLEMENTO_PACOTE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPacote", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodPacote
		{
			get
			{
				return this._CodPacote;
			}
			set
			{
				if ((this._CodPacote != value))
				{
					this._CodPacote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodSuplemento", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodSuplemento
		{
			get
			{
				return this._CodSuplemento;
			}
			set
			{
				if ((this._CodSuplemento != value))
				{
					this._CodSuplemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantidade", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this._Quantidade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdDisponivel", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> QtdDisponivel
		{
			get
			{
				return this._QtdDisponivel;
			}
			set
			{
				if ((this._QtdDisponivel != value))
				{
					this._QtdDisponivel = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AGENDAMENTO")]
	public partial class AGENDAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodAgendamento;
		
		private string _CPFCliente;
		
		private int _CodPacote;
		
		private System.Nullable<int> _QtdPessoas;
		
		private System.Nullable<System.DateTime> _DateRegistro;
		
		private System.Nullable<System.DateTime> _DataAgendada;
		
		private System.Nullable<int> _QtdPessoasSemEquipamento;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
		private EntityRef<PACOTE> _PACOTE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodAgendamentoChanging(int value);
    partial void OnCodAgendamentoChanged();
    partial void OnCPFClienteChanging(string value);
    partial void OnCPFClienteChanged();
    partial void OnCodPacoteChanging(int value);
    partial void OnCodPacoteChanged();
    partial void OnQtdPessoasChanging(System.Nullable<int> value);
    partial void OnQtdPessoasChanged();
    partial void OnDateRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnDateRegistroChanged();
    partial void OnDataAgendadaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataAgendadaChanged();
    partial void OnQtdPessoasSemEquipamentoChanging(System.Nullable<int> value);
    partial void OnQtdPessoasSemEquipamentoChanged();
    #endregion
		
		public AGENDAMENTO()
		{
			this._CLIENTE = default(EntityRef<CLIENTE>);
			this._PACOTE = default(EntityRef<PACOTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodAgendamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CodAgendamento
		{
			get
			{
				return this._CodAgendamento;
			}
			set
			{
				if ((this._CodAgendamento != value))
				{
					this.OnCodAgendamentoChanging(value);
					this.SendPropertyChanging();
					this._CodAgendamento = value;
					this.SendPropertyChanged("CodAgendamento");
					this.OnCodAgendamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCliente", DbType="NVarChar(14) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CPFCliente
		{
			get
			{
				return this._CPFCliente;
			}
			set
			{
				if ((this._CPFCliente != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCPFClienteChanging(value);
					this.SendPropertyChanging();
					this._CPFCliente = value;
					this.SendPropertyChanged("CPFCliente");
					this.OnCPFClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPacote", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodPacote
		{
			get
			{
				return this._CodPacote;
			}
			set
			{
				if ((this._CodPacote != value))
				{
					if (this._PACOTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodPacoteChanging(value);
					this.SendPropertyChanging();
					this._CodPacote = value;
					this.SendPropertyChanged("CodPacote");
					this.OnCodPacoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdPessoas", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> QtdPessoas
		{
			get
			{
				return this._QtdPessoas;
			}
			set
			{
				if ((this._QtdPessoas != value))
				{
					this.OnQtdPessoasChanging(value);
					this.SendPropertyChanging();
					this._QtdPessoas = value;
					this.SendPropertyChanged("QtdPessoas");
					this.OnQtdPessoasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRegistro", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DateRegistro
		{
			get
			{
				return this._DateRegistro;
			}
			set
			{
				if ((this._DateRegistro != value))
				{
					this.OnDateRegistroChanging(value);
					this.SendPropertyChanging();
					this._DateRegistro = value;
					this.SendPropertyChanged("DateRegistro");
					this.OnDateRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAgendada", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DataAgendada
		{
			get
			{
				return this._DataAgendada;
			}
			set
			{
				if ((this._DataAgendada != value))
				{
					this.OnDataAgendadaChanging(value);
					this.SendPropertyChanging();
					this._DataAgendada = value;
					this.SendPropertyChanged("DataAgendada");
					this.OnDataAgendadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdPessoasSemEquipamento", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> QtdPessoasSemEquipamento
		{
			get
			{
				return this._QtdPessoasSemEquipamento;
			}
			set
			{
				if ((this._QtdPessoasSemEquipamento != value))
				{
					this.OnQtdPessoasSemEquipamentoChanging(value);
					this.SendPropertyChanging();
					this._QtdPessoasSemEquipamento = value;
					this.SendPropertyChanged("QtdPessoasSemEquipamento");
					this.OnQtdPessoasSemEquipamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_AGENDAMENTO", Storage="_CLIENTE", ThisKey="CPFCliente", OtherKey="CPF", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.AGENDAMENTOs.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.AGENDAMENTOs.Add(this);
						this._CPFCliente = value.CPF;
					}
					else
					{
						this._CPFCliente = default(string);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PACOTE_AGENDAMENTO", Storage="_PACOTE", ThisKey="CodPacote", OtherKey="CodPacote", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public PACOTE PACOTE
		{
			get
			{
				return this._PACOTE.Entity;
			}
			set
			{
				PACOTE previousValue = this._PACOTE.Entity;
				if (((previousValue != value) 
							|| (this._PACOTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PACOTE.Entity = null;
						previousValue.AGENDAMENTOs.Remove(this);
					}
					this._PACOTE.Entity = value;
					if ((value != null))
					{
						value.AGENDAMENTOs.Add(this);
						this._CodPacote = value.CodPacote;
					}
					else
					{
						this._CodPacote = default(int);
					}
					this.SendPropertyChanged("PACOTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CPF;
		
		private string _Nome;
		
		private string _Endereço;
		
		private string _Telefone;
		
		private string _E_mail;
		
		private System.Nullable<System.DateTime> _DataCadastro;
		
		private EntitySet<AGENDAMENTO> _AGENDAMENTOs;
		
		private EntitySet<CLIENTE_CURSO> _CLIENTE_CURSOs;
		
		private EntitySet<VENDA> _VENDAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEndereçoChanging(string value);
    partial void OnEndereçoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnE_mailChanging(string value);
    partial void OnE_mailChanged();
    partial void OnDataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCadastroChanged();
    #endregion
		
		public CLIENTE()
		{
			this._AGENDAMENTOs = new EntitySet<AGENDAMENTO>(new Action<AGENDAMENTO>(this.attach_AGENDAMENTOs), new Action<AGENDAMENTO>(this.detach_AGENDAMENTOs));
			this._CLIENTE_CURSOs = new EntitySet<CLIENTE_CURSO>(new Action<CLIENTE_CURSO>(this.attach_CLIENTE_CURSOs), new Action<CLIENTE_CURSO>(this.detach_CLIENTE_CURSOs));
			this._VENDAs = new EntitySet<VENDA>(new Action<VENDA>(this.attach_VENDAs), new Action<VENDA>(this.detach_VENDAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="NVarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereço", DbType="NVarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string Endereço
		{
			get
			{
				return this._Endereço;
			}
			set
			{
				if ((this._Endereço != value))
				{
					this.OnEndereçoChanging(value);
					this.SendPropertyChanging();
					this._Endereço = value;
					this.SendPropertyChanged("Endereço");
					this.OnEndereçoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail]", Storage="_E_mail", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string E_mail
		{
			get
			{
				return this._E_mail;
			}
			set
			{
				if ((this._E_mail != value))
				{
					this.OnE_mailChanging(value);
					this.SendPropertyChanging();
					this._E_mail = value;
					this.SendPropertyChanged("E_mail");
					this.OnE_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_AGENDAMENTO", Storage="_AGENDAMENTOs", ThisKey="CPF", OtherKey="CPFCliente")]
		public EntitySet<AGENDAMENTO> AGENDAMENTOs
		{
			get
			{
				return this._AGENDAMENTOs;
			}
			set
			{
				this._AGENDAMENTOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_CLIENTE_CURSO", Storage="_CLIENTE_CURSOs", ThisKey="CPF", OtherKey="CPFCliente")]
		public EntitySet<CLIENTE_CURSO> CLIENTE_CURSOs
		{
			get
			{
				return this._CLIENTE_CURSOs;
			}
			set
			{
				this._CLIENTE_CURSOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_VENDA", Storage="_VENDAs", ThisKey="CPF", OtherKey="CPFCliente")]
		public EntitySet<VENDA> VENDAs
		{
			get
			{
				return this._VENDAs;
			}
			set
			{
				this._VENDAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AGENDAMENTOs(AGENDAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_AGENDAMENTOs(AGENDAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
		
		private void attach_CLIENTE_CURSOs(CLIENTE_CURSO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_CLIENTE_CURSOs(CLIENTE_CURSO entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
		
		private void attach_VENDAs(VENDA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_VENDAs(VENDA entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[CLIENTE-CURSO]")]
	public partial class CLIENTE_CURSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodCurso;
		
		private string _CPFCliente;
		
		private System.Nullable<System.DateTime> _DataMatricula;
		
		private string _Turma;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
		private EntityRef<CURSO> _CURSO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodCursoChanging(int value);
    partial void OnCodCursoChanged();
    partial void OnCPFClienteChanging(string value);
    partial void OnCPFClienteChanged();
    partial void OnDataMatriculaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataMatriculaChanged();
    partial void OnTurmaChanging(string value);
    partial void OnTurmaChanged();
    #endregion
		
		public CLIENTE_CURSO()
		{
			this._CLIENTE = default(EntityRef<CLIENTE>);
			this._CURSO = default(EntityRef<CURSO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCurso", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int CodCurso
		{
			get
			{
				return this._CodCurso;
			}
			set
			{
				if ((this._CodCurso != value))
				{
					if (this._CURSO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCursoChanging(value);
					this.SendPropertyChanging();
					this._CodCurso = value;
					this.SendPropertyChanged("CodCurso");
					this.OnCodCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCliente", DbType="NVarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string CPFCliente
		{
			get
			{
				return this._CPFCliente;
			}
			set
			{
				if ((this._CPFCliente != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCPFClienteChanging(value);
					this.SendPropertyChanging();
					this._CPFCliente = value;
					this.SendPropertyChanged("CPFCliente");
					this.OnCPFClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataMatricula", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DataMatricula
		{
			get
			{
				return this._DataMatricula;
			}
			set
			{
				if ((this._DataMatricula != value))
				{
					this.OnDataMatriculaChanging(value);
					this.SendPropertyChanging();
					this._DataMatricula = value;
					this.SendPropertyChanged("DataMatricula");
					this.OnDataMatriculaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Turma", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Turma
		{
			get
			{
				return this._Turma;
			}
			set
			{
				if ((this._Turma != value))
				{
					this.OnTurmaChanging(value);
					this.SendPropertyChanging();
					this._Turma = value;
					this.SendPropertyChanged("Turma");
					this.OnTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_CLIENTE_CURSO", Storage="_CLIENTE", ThisKey="CPFCliente", OtherKey="CPF", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.CLIENTE_CURSOs.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.CLIENTE_CURSOs.Add(this);
						this._CPFCliente = value.CPF;
					}
					else
					{
						this._CPFCliente = default(string);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSO_CLIENTE_CURSO", Storage="_CURSO", ThisKey="CodCurso", OtherKey="CodCurso", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CURSO CURSO
		{
			get
			{
				return this._CURSO.Entity;
			}
			set
			{
				CURSO previousValue = this._CURSO.Entity;
				if (((previousValue != value) 
							|| (this._CURSO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CURSO.Entity = null;
						previousValue.CLIENTE_CURSOs.Remove(this);
					}
					this._CURSO.Entity = value;
					if ((value != null))
					{
						value.CLIENTE_CURSOs.Add(this);
						this._CodCurso = value.CodCurso;
					}
					else
					{
						this._CodCurso = default(int);
					}
					this.SendPropertyChanged("CURSO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CURSO")]
	public partial class CURSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodCurso;
		
		private string _Nome;
		
		private string _CPFInstrutor;
		
		private System.Nullable<int> _Horas;
		
		private System.Nullable<decimal> _Preco;
		
		private System.Nullable<int> _NumeroPessoasTurma;
		
		private EntitySet<CLIENTE_CURSO> _CLIENTE_CURSOs;
		
		private EntityRef<INSTRUTOR> _INSTRUTOR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodCursoChanging(int value);
    partial void OnCodCursoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCPFInstrutorChanging(string value);
    partial void OnCPFInstrutorChanged();
    partial void OnHorasChanging(System.Nullable<int> value);
    partial void OnHorasChanged();
    partial void OnPrecoChanging(System.Nullable<decimal> value);
    partial void OnPrecoChanged();
    partial void OnNumeroPessoasTurmaChanging(System.Nullable<int> value);
    partial void OnNumeroPessoasTurmaChanged();
    #endregion
		
		public CURSO()
		{
			this._CLIENTE_CURSOs = new EntitySet<CLIENTE_CURSO>(new Action<CLIENTE_CURSO>(this.attach_CLIENTE_CURSOs), new Action<CLIENTE_CURSO>(this.detach_CLIENTE_CURSOs));
			this._INSTRUTOR = default(EntityRef<INSTRUTOR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCurso", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CodCurso
		{
			get
			{
				return this._CodCurso;
			}
			set
			{
				if ((this._CodCurso != value))
				{
					this.OnCodCursoChanging(value);
					this.SendPropertyChanging();
					this._CodCurso = value;
					this.SendPropertyChanged("CodCurso");
					this.OnCodCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFInstrutor", DbType="NVarChar(14) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CPFInstrutor
		{
			get
			{
				return this._CPFInstrutor;
			}
			set
			{
				if ((this._CPFInstrutor != value))
				{
					if (this._INSTRUTOR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCPFInstrutorChanging(value);
					this.SendPropertyChanging();
					this._CPFInstrutor = value;
					this.SendPropertyChanged("CPFInstrutor");
					this.OnCPFInstrutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horas", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Horas
		{
			get
			{
				return this._Horas;
			}
			set
			{
				if ((this._Horas != value))
				{
					this.OnHorasChanging(value);
					this.SendPropertyChanging();
					this._Horas = value;
					this.SendPropertyChanged("Horas");
					this.OnHorasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preco", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Preco
		{
			get
			{
				return this._Preco;
			}
			set
			{
				if ((this._Preco != value))
				{
					this.OnPrecoChanging(value);
					this.SendPropertyChanging();
					this._Preco = value;
					this.SendPropertyChanged("Preco");
					this.OnPrecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPessoasTurma", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NumeroPessoasTurma
		{
			get
			{
				return this._NumeroPessoasTurma;
			}
			set
			{
				if ((this._NumeroPessoasTurma != value))
				{
					this.OnNumeroPessoasTurmaChanging(value);
					this.SendPropertyChanging();
					this._NumeroPessoasTurma = value;
					this.SendPropertyChanged("NumeroPessoasTurma");
					this.OnNumeroPessoasTurmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSO_CLIENTE_CURSO", Storage="_CLIENTE_CURSOs", ThisKey="CodCurso", OtherKey="CodCurso")]
		public EntitySet<CLIENTE_CURSO> CLIENTE_CURSOs
		{
			get
			{
				return this._CLIENTE_CURSOs;
			}
			set
			{
				this._CLIENTE_CURSOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INSTRUTOR_CURSO", Storage="_INSTRUTOR", ThisKey="CPFInstrutor", OtherKey="CPF", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public INSTRUTOR INSTRUTOR
		{
			get
			{
				return this._INSTRUTOR.Entity;
			}
			set
			{
				INSTRUTOR previousValue = this._INSTRUTOR.Entity;
				if (((previousValue != value) 
							|| (this._INSTRUTOR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._INSTRUTOR.Entity = null;
						previousValue.CURSOs.Remove(this);
					}
					this._INSTRUTOR.Entity = value;
					if ((value != null))
					{
						value.CURSOs.Add(this);
						this._CPFInstrutor = value.CPF;
					}
					else
					{
						this._CPFInstrutor = default(string);
					}
					this.SendPropertyChanged("INSTRUTOR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CLIENTE_CURSOs(CLIENTE_CURSO entity)
		{
			this.SendPropertyChanging();
			entity.CURSO = this;
		}
		
		private void detach_CLIENTE_CURSOs(CLIENTE_CURSO entity)
		{
			this.SendPropertyChanging();
			entity.CURSO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EQUIPAMENTO")]
	public partial class EQUIPAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodEquipamento;
		
		private string _Nome;
		
		private string _Tipo;
		
		private System.Nullable<int> _QtdEstoque;
		
		private System.Nullable<decimal> _Preco;
		
		private EntitySet<EQUIPAMENTO_VENDA> _EQUIPAMENTO_VENDAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodEquipamentoChanging(int value);
    partial void OnCodEquipamentoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnQtdEstoqueChanging(System.Nullable<int> value);
    partial void OnQtdEstoqueChanged();
    partial void OnPrecoChanging(System.Nullable<decimal> value);
    partial void OnPrecoChanged();
    #endregion
		
		public EQUIPAMENTO()
		{
			this._EQUIPAMENTO_VENDAs = new EntitySet<EQUIPAMENTO_VENDA>(new Action<EQUIPAMENTO_VENDA>(this.attach_EQUIPAMENTO_VENDAs), new Action<EQUIPAMENTO_VENDA>(this.detach_EQUIPAMENTO_VENDAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodEquipamento", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int CodEquipamento
		{
			get
			{
				return this._CodEquipamento;
			}
			set
			{
				if ((this._CodEquipamento != value))
				{
					this.OnCodEquipamentoChanging(value);
					this.SendPropertyChanging();
					this._CodEquipamento = value;
					this.SendPropertyChanged("CodEquipamento");
					this.OnCodEquipamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdEstoque", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> QtdEstoque
		{
			get
			{
				return this._QtdEstoque;
			}
			set
			{
				if ((this._QtdEstoque != value))
				{
					this.OnQtdEstoqueChanging(value);
					this.SendPropertyChanging();
					this._QtdEstoque = value;
					this.SendPropertyChanged("QtdEstoque");
					this.OnQtdEstoqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preco", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Preco
		{
			get
			{
				return this._Preco;
			}
			set
			{
				if ((this._Preco != value))
				{
					this.OnPrecoChanging(value);
					this.SendPropertyChanging();
					this._Preco = value;
					this.SendPropertyChanged("Preco");
					this.OnPrecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EQUIPAMENTO_EQUIPAMENTO_VENDA", Storage="_EQUIPAMENTO_VENDAs", ThisKey="CodEquipamento", OtherKey="CodEquipamento")]
		public EntitySet<EQUIPAMENTO_VENDA> EQUIPAMENTO_VENDAs
		{
			get
			{
				return this._EQUIPAMENTO_VENDAs;
			}
			set
			{
				this._EQUIPAMENTO_VENDAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EQUIPAMENTO_VENDAs(EQUIPAMENTO_VENDA entity)
		{
			this.SendPropertyChanging();
			entity.EQUIPAMENTO = this;
		}
		
		private void detach_EQUIPAMENTO_VENDAs(EQUIPAMENTO_VENDA entity)
		{
			this.SendPropertyChanging();
			entity.EQUIPAMENTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[EQUIPAMENTO-VENDA]")]
	public partial class EQUIPAMENTO_VENDA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodVenda;
		
		private int _CodEquipamento;
		
		private System.Nullable<int> _Quantidade;
		
		private EntityRef<EQUIPAMENTO> _EQUIPAMENTO;
		
		private EntityRef<VENDA> _VENDA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodVendaChanging(int value);
    partial void OnCodVendaChanged();
    partial void OnCodEquipamentoChanging(int value);
    partial void OnCodEquipamentoChanged();
    partial void OnQuantidadeChanging(System.Nullable<int> value);
    partial void OnQuantidadeChanged();
    #endregion
		
		public EQUIPAMENTO_VENDA()
		{
			this._EQUIPAMENTO = default(EntityRef<EQUIPAMENTO>);
			this._VENDA = default(EntityRef<VENDA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodVenda", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int CodVenda
		{
			get
			{
				return this._CodVenda;
			}
			set
			{
				if ((this._CodVenda != value))
				{
					if (this._VENDA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodVendaChanging(value);
					this.SendPropertyChanging();
					this._CodVenda = value;
					this.SendPropertyChanged("CodVenda");
					this.OnCodVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodEquipamento", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int CodEquipamento
		{
			get
			{
				return this._CodEquipamento;
			}
			set
			{
				if ((this._CodEquipamento != value))
				{
					if (this._EQUIPAMENTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodEquipamentoChanging(value);
					this.SendPropertyChanging();
					this._CodEquipamento = value;
					this.SendPropertyChanged("CodEquipamento");
					this.OnCodEquipamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantidade", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EQUIPAMENTO_EQUIPAMENTO_VENDA", Storage="_EQUIPAMENTO", ThisKey="CodEquipamento", OtherKey="CodEquipamento", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public EQUIPAMENTO EQUIPAMENTO
		{
			get
			{
				return this._EQUIPAMENTO.Entity;
			}
			set
			{
				EQUIPAMENTO previousValue = this._EQUIPAMENTO.Entity;
				if (((previousValue != value) 
							|| (this._EQUIPAMENTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EQUIPAMENTO.Entity = null;
						previousValue.EQUIPAMENTO_VENDAs.Remove(this);
					}
					this._EQUIPAMENTO.Entity = value;
					if ((value != null))
					{
						value.EQUIPAMENTO_VENDAs.Add(this);
						this._CodEquipamento = value.CodEquipamento;
					}
					else
					{
						this._CodEquipamento = default(int);
					}
					this.SendPropertyChanged("EQUIPAMENTO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDA_EQUIPAMENTO_VENDA", Storage="_VENDA", ThisKey="CodVenda", OtherKey="CodVenda", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public VENDA VENDA
		{
			get
			{
				return this._VENDA.Entity;
			}
			set
			{
				VENDA previousValue = this._VENDA.Entity;
				if (((previousValue != value) 
							|| (this._VENDA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VENDA.Entity = null;
						previousValue.EQUIPAMENTO_VENDAs.Remove(this);
					}
					this._VENDA.Entity = value;
					if ((value != null))
					{
						value.EQUIPAMENTO_VENDAs.Add(this);
						this._CodVenda = value.CodVenda;
					}
					else
					{
						this._CodVenda = default(int);
					}
					this.SendPropertyChanged("VENDA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.INSTRUTOR")]
	public partial class INSTRUTOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CPF;
		
		private string _Nome;
		
		private string _Endereço;
		
		private string _Telefone;
		
		private string _E_mail;
		
		private System.Nullable<System.DateTime> _DataCadastro;
		
		private System.Nullable<bool> _Certificado;
		
		private EntitySet<CURSO> _CURSOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEndereçoChanging(string value);
    partial void OnEndereçoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnE_mailChanging(string value);
    partial void OnE_mailChanged();
    partial void OnDataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCadastroChanged();
    partial void OnCertificadoChanging(System.Nullable<bool> value);
    partial void OnCertificadoChanged();
    #endregion
		
		public INSTRUTOR()
		{
			this._CURSOs = new EntitySet<CURSO>(new Action<CURSO>(this.attach_CURSOs), new Action<CURSO>(this.detach_CURSOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="NVarChar(14) NOT NULL", CanBeNull=false, IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereço", DbType="NVarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string Endereço
		{
			get
			{
				return this._Endereço;
			}
			set
			{
				if ((this._Endereço != value))
				{
					this.OnEndereçoChanging(value);
					this.SendPropertyChanging();
					this._Endereço = value;
					this.SendPropertyChanged("Endereço");
					this.OnEndereçoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail]", Storage="_E_mail", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string E_mail
		{
			get
			{
				return this._E_mail;
			}
			set
			{
				if ((this._E_mail != value))
				{
					this.OnE_mailChanging(value);
					this.SendPropertyChanging();
					this._E_mail = value;
					this.SendPropertyChanged("E_mail");
					this.OnE_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Certificado", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> Certificado
		{
			get
			{
				return this._Certificado;
			}
			set
			{
				if ((this._Certificado != value))
				{
					this.OnCertificadoChanging(value);
					this.SendPropertyChanging();
					this._Certificado = value;
					this.SendPropertyChanged("Certificado");
					this.OnCertificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="INSTRUTOR_CURSO", Storage="_CURSOs", ThisKey="CPF", OtherKey="CPFInstrutor")]
		public EntitySet<CURSO> CURSOs
		{
			get
			{
				return this._CURSOs;
			}
			set
			{
				this._CURSOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOs(CURSO entity)
		{
			this.SendPropertyChanging();
			entity.INSTRUTOR = this;
		}
		
		private void detach_CURSOs(CURSO entity)
		{
			this.SendPropertyChanging();
			entity.INSTRUTOR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PACOTE")]
	public partial class PACOTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodPacote;
		
		private string _Nome;
		
		private string _Local;
		
		private System.Nullable<int> _NumeroPessoasMax;
		
		private System.Nullable<decimal> _Preco;
		
		private EntitySet<AGENDAMENTO> _AGENDAMENTOs;
		
		private EntitySet<SUPLEMENTO_PACOTE> _SUPLEMENTO_PACOTEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodPacoteChanging(int value);
    partial void OnCodPacoteChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnLocalChanging(string value);
    partial void OnLocalChanged();
    partial void OnNumeroPessoasMaxChanging(System.Nullable<int> value);
    partial void OnNumeroPessoasMaxChanged();
    partial void OnPrecoChanging(System.Nullable<decimal> value);
    partial void OnPrecoChanged();
    #endregion
		
		public PACOTE()
		{
			this._AGENDAMENTOs = new EntitySet<AGENDAMENTO>(new Action<AGENDAMENTO>(this.attach_AGENDAMENTOs), new Action<AGENDAMENTO>(this.detach_AGENDAMENTOs));
			this._SUPLEMENTO_PACOTEs = new EntitySet<SUPLEMENTO_PACOTE>(new Action<SUPLEMENTO_PACOTE>(this.attach_SUPLEMENTO_PACOTEs), new Action<SUPLEMENTO_PACOTE>(this.detach_SUPLEMENTO_PACOTEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPacote", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CodPacote
		{
			get
			{
				return this._CodPacote;
			}
			set
			{
				if ((this._CodPacote != value))
				{
					this.OnCodPacoteChanging(value);
					this.SendPropertyChanging();
					this._CodPacote = value;
					this.SendPropertyChanged("CodPacote");
					this.OnCodPacoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Local", DbType="NVarChar(80)", UpdateCheck=UpdateCheck.Never)]
		public string Local
		{
			get
			{
				return this._Local;
			}
			set
			{
				if ((this._Local != value))
				{
					this.OnLocalChanging(value);
					this.SendPropertyChanging();
					this._Local = value;
					this.SendPropertyChanged("Local");
					this.OnLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPessoasMax", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NumeroPessoasMax
		{
			get
			{
				return this._NumeroPessoasMax;
			}
			set
			{
				if ((this._NumeroPessoasMax != value))
				{
					this.OnNumeroPessoasMaxChanging(value);
					this.SendPropertyChanging();
					this._NumeroPessoasMax = value;
					this.SendPropertyChanged("NumeroPessoasMax");
					this.OnNumeroPessoasMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preco", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Preco
		{
			get
			{
				return this._Preco;
			}
			set
			{
				if ((this._Preco != value))
				{
					this.OnPrecoChanging(value);
					this.SendPropertyChanging();
					this._Preco = value;
					this.SendPropertyChanged("Preco");
					this.OnPrecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PACOTE_AGENDAMENTO", Storage="_AGENDAMENTOs", ThisKey="CodPacote", OtherKey="CodPacote")]
		public EntitySet<AGENDAMENTO> AGENDAMENTOs
		{
			get
			{
				return this._AGENDAMENTOs;
			}
			set
			{
				this._AGENDAMENTOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PACOTE_SUPLEMENTO_PACOTE", Storage="_SUPLEMENTO_PACOTEs", ThisKey="CodPacote", OtherKey="CodPacote")]
		public EntitySet<SUPLEMENTO_PACOTE> SUPLEMENTO_PACOTEs
		{
			get
			{
				return this._SUPLEMENTO_PACOTEs;
			}
			set
			{
				this._SUPLEMENTO_PACOTEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AGENDAMENTOs(AGENDAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.PACOTE = this;
		}
		
		private void detach_AGENDAMENTOs(AGENDAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.PACOTE = null;
		}
		
		private void attach_SUPLEMENTO_PACOTEs(SUPLEMENTO_PACOTE entity)
		{
			this.SendPropertyChanging();
			entity.PACOTE = this;
		}
		
		private void detach_SUPLEMENTO_PACOTEs(SUPLEMENTO_PACOTE entity)
		{
			this.SendPropertyChanging();
			entity.PACOTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SUPLEMENTO")]
	public partial class SUPLEMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodSuplemento;
		
		private string _Nome;
		
		private string _Tipo;
		
		private System.Nullable<int> _QtdDisponivel;
		
		private EntitySet<SUPLEMENTO_PACOTE> _SUPLEMENTO_PACOTEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodSuplementoChanging(int value);
    partial void OnCodSuplementoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnQtdDisponivelChanging(System.Nullable<int> value);
    partial void OnQtdDisponivelChanged();
    #endregion
		
		public SUPLEMENTO()
		{
			this._SUPLEMENTO_PACOTEs = new EntitySet<SUPLEMENTO_PACOTE>(new Action<SUPLEMENTO_PACOTE>(this.attach_SUPLEMENTO_PACOTEs), new Action<SUPLEMENTO_PACOTE>(this.detach_SUPLEMENTO_PACOTEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodSuplemento", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int CodSuplemento
		{
			get
			{
				return this._CodSuplemento;
			}
			set
			{
				if ((this._CodSuplemento != value))
				{
					this.OnCodSuplementoChanging(value);
					this.SendPropertyChanging();
					this._CodSuplemento = value;
					this.SendPropertyChanged("CodSuplemento");
					this.OnCodSuplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdDisponivel", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> QtdDisponivel
		{
			get
			{
				return this._QtdDisponivel;
			}
			set
			{
				if ((this._QtdDisponivel != value))
				{
					this.OnQtdDisponivelChanging(value);
					this.SendPropertyChanging();
					this._QtdDisponivel = value;
					this.SendPropertyChanged("QtdDisponivel");
					this.OnQtdDisponivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SUPLEMENTO_SUPLEMENTO_PACOTE", Storage="_SUPLEMENTO_PACOTEs", ThisKey="CodSuplemento", OtherKey="CodSuplemento")]
		public EntitySet<SUPLEMENTO_PACOTE> SUPLEMENTO_PACOTEs
		{
			get
			{
				return this._SUPLEMENTO_PACOTEs;
			}
			set
			{
				this._SUPLEMENTO_PACOTEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SUPLEMENTO_PACOTEs(SUPLEMENTO_PACOTE entity)
		{
			this.SendPropertyChanging();
			entity.SUPLEMENTO = this;
		}
		
		private void detach_SUPLEMENTO_PACOTEs(SUPLEMENTO_PACOTE entity)
		{
			this.SendPropertyChanging();
			entity.SUPLEMENTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[SUPLEMENTO-PACOTE]")]
	public partial class SUPLEMENTO_PACOTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodPacote;
		
		private int _CodSuplemento;
		
		private System.Nullable<int> _Quantidade;
		
		private EntityRef<PACOTE> _PACOTE;
		
		private EntityRef<SUPLEMENTO> _SUPLEMENTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodPacoteChanging(int value);
    partial void OnCodPacoteChanged();
    partial void OnCodSuplementoChanging(int value);
    partial void OnCodSuplementoChanged();
    partial void OnQuantidadeChanging(System.Nullable<int> value);
    partial void OnQuantidadeChanged();
    #endregion
		
		public SUPLEMENTO_PACOTE()
		{
			this._PACOTE = default(EntityRef<PACOTE>);
			this._SUPLEMENTO = default(EntityRef<SUPLEMENTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPacote", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int CodPacote
		{
			get
			{
				return this._CodPacote;
			}
			set
			{
				if ((this._CodPacote != value))
				{
					if (this._PACOTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodPacoteChanging(value);
					this.SendPropertyChanging();
					this._CodPacote = value;
					this.SendPropertyChanged("CodPacote");
					this.OnCodPacoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodSuplemento", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int CodSuplemento
		{
			get
			{
				return this._CodSuplemento;
			}
			set
			{
				if ((this._CodSuplemento != value))
				{
					if (this._SUPLEMENTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodSuplementoChanging(value);
					this.SendPropertyChanging();
					this._CodSuplemento = value;
					this.SendPropertyChanged("CodSuplemento");
					this.OnCodSuplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantidade", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PACOTE_SUPLEMENTO_PACOTE", Storage="_PACOTE", ThisKey="CodPacote", OtherKey="CodPacote", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public PACOTE PACOTE
		{
			get
			{
				return this._PACOTE.Entity;
			}
			set
			{
				PACOTE previousValue = this._PACOTE.Entity;
				if (((previousValue != value) 
							|| (this._PACOTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PACOTE.Entity = null;
						previousValue.SUPLEMENTO_PACOTEs.Remove(this);
					}
					this._PACOTE.Entity = value;
					if ((value != null))
					{
						value.SUPLEMENTO_PACOTEs.Add(this);
						this._CodPacote = value.CodPacote;
					}
					else
					{
						this._CodPacote = default(int);
					}
					this.SendPropertyChanged("PACOTE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SUPLEMENTO_SUPLEMENTO_PACOTE", Storage="_SUPLEMENTO", ThisKey="CodSuplemento", OtherKey="CodSuplemento", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public SUPLEMENTO SUPLEMENTO
		{
			get
			{
				return this._SUPLEMENTO.Entity;
			}
			set
			{
				SUPLEMENTO previousValue = this._SUPLEMENTO.Entity;
				if (((previousValue != value) 
							|| (this._SUPLEMENTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SUPLEMENTO.Entity = null;
						previousValue.SUPLEMENTO_PACOTEs.Remove(this);
					}
					this._SUPLEMENTO.Entity = value;
					if ((value != null))
					{
						value.SUPLEMENTO_PACOTEs.Add(this);
						this._CodSuplemento = value.CodSuplemento;
					}
					else
					{
						this._CodSuplemento = default(int);
					}
					this.SendPropertyChanged("SUPLEMENTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VENDA")]
	public partial class VENDA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodVenda;
		
		private string _CPFCliente;
		
		private System.Nullable<System.DateTime> _DataVenda;
		
		private EntitySet<EQUIPAMENTO_VENDA> _EQUIPAMENTO_VENDAs;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodVendaChanging(int value);
    partial void OnCodVendaChanged();
    partial void OnCPFClienteChanging(string value);
    partial void OnCPFClienteChanged();
    partial void OnDataVendaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataVendaChanged();
    #endregion
		
		public VENDA()
		{
			this._EQUIPAMENTO_VENDAs = new EntitySet<EQUIPAMENTO_VENDA>(new Action<EQUIPAMENTO_VENDA>(this.attach_EQUIPAMENTO_VENDAs), new Action<EQUIPAMENTO_VENDA>(this.detach_EQUIPAMENTO_VENDAs));
			this._CLIENTE = default(EntityRef<CLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodVenda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int CodVenda
		{
			get
			{
				return this._CodVenda;
			}
			set
			{
				if ((this._CodVenda != value))
				{
					this.OnCodVendaChanging(value);
					this.SendPropertyChanging();
					this._CodVenda = value;
					this.SendPropertyChanged("CodVenda");
					this.OnCodVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPFCliente", DbType="NVarChar(14) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CPFCliente
		{
			get
			{
				return this._CPFCliente;
			}
			set
			{
				if ((this._CPFCliente != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCPFClienteChanging(value);
					this.SendPropertyChanging();
					this._CPFCliente = value;
					this.SendPropertyChanged("CPFCliente");
					this.OnCPFClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataVenda", DbType="Date", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> DataVenda
		{
			get
			{
				return this._DataVenda;
			}
			set
			{
				if ((this._DataVenda != value))
				{
					this.OnDataVendaChanging(value);
					this.SendPropertyChanging();
					this._DataVenda = value;
					this.SendPropertyChanged("DataVenda");
					this.OnDataVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VENDA_EQUIPAMENTO_VENDA", Storage="_EQUIPAMENTO_VENDAs", ThisKey="CodVenda", OtherKey="CodVenda")]
		public EntitySet<EQUIPAMENTO_VENDA> EQUIPAMENTO_VENDAs
		{
			get
			{
				return this._EQUIPAMENTO_VENDAs;
			}
			set
			{
				this._EQUIPAMENTO_VENDAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_VENDA", Storage="_CLIENTE", ThisKey="CPFCliente", OtherKey="CPF", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.VENDAs.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.VENDAs.Add(this);
						this._CPFCliente = value.CPF;
					}
					else
					{
						this._CPFCliente = default(string);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EQUIPAMENTO_VENDAs(EQUIPAMENTO_VENDA entity)
		{
			this.SendPropertyChanging();
			entity.VENDA = this;
		}
		
		private void detach_EQUIPAMENTO_VENDAs(EQUIPAMENTO_VENDA entity)
		{
			this.SendPropertyChanging();
			entity.VENDA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_EQUIPVENDA")]
	public partial class VW_EQUIPVENDA
	{
		
		private int _CodVenda;
		
		private int _CodEquipamento;
		
		private System.Nullable<int> _Quantidade;
		
		private string _Nome;
		
		private System.Nullable<decimal> _Preco;
		
		private System.Nullable<decimal> _PrecoTotal;
		
		public VW_EQUIPVENDA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodVenda", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodVenda
		{
			get
			{
				return this._CodVenda;
			}
			set
			{
				if ((this._CodVenda != value))
				{
					this._CodVenda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodEquipamento", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int CodEquipamento
		{
			get
			{
				return this._CodEquipamento;
			}
			set
			{
				if ((this._CodEquipamento != value))
				{
					this._CodEquipamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantidade", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this._Quantidade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preco", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Preco
		{
			get
			{
				return this._Preco;
			}
			set
			{
				if ((this._Preco != value))
				{
					this._Preco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecoTotal", DbType="Money", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> PrecoTotal
		{
			get
			{
				return this._PrecoTotal;
			}
			set
			{
				if ((this._PrecoTotal != value))
				{
					this._PrecoTotal = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
